#!/bin/sh

# PLX build script

# compile options
compileForSpeed="-DNDEBUG -std=c17 -Wall -O3 -ffast-math"
compileForSize="-DNDEBUG -std=c17 -Wall -Os"
# the switch-enum is a bit much
# compileForDebug="-DDEBUG -std=c17  -Wextra -Wswitch-enum -pedantic -g -O0"
compileForDebug="-DDEBUG -std=c17 -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -pedantic -g -O0"
compileForDebugWithMemCheck="-DDEBUG -std=c17 -Wall -fsanitize=address -g -O0"  # must also use clang
# the -fsanitize=address option is currently not useful because memory is managed internally

options="$compileForDebug"

CC=clang
# CC=gcc
# CC=tcc

mkdir -p bin lib
rm bin/*
rm -rf lib/*

# compile all the source files into .o files
cd lib
sources=$(find ../src -name *.c ! -name main.c)
echo $CC $options -c -I ../src $sources
$CC $options -c -I ../src $sources
if [ $? -ne 0 ]; then
    exit 1
fi
# build the archive library and then remove the .o files
ar rcs libplx.a *.o
rm *.o
cd ..

# build the main executable concurrently
echo $CC $options -o bin/plx -I src -Llib src/main.c -lplx
$CC $options -o bin/plx -I src -Llib src/main.c -lplx &

# build each test executable concurrently
testDir=tests
testSources=$(find ${testDir} -name *.c ! -name main.c)
for sourceFile in ${testSources}; do
    f=$(basename $sourceFile .c)
    s="${f%_test}"
    exeFile=bin/$f
    # echo $CC $options -o $exeFile -I src -I ${testDir} $sourceFile -Llib -lplx
    $CC $options -o $exeFile -I src -I ${testDir} $sourceFile -Llib -lplx &
done
